#!/usr/bin/expect
  2 set timeout -1
  3 set file_name [lindex $argv 0]
  4 set remote_pwd [lindex $argv 1]
  5 spawn scp -r $file_name zhoulijun@192.168.8.66:${remote_pwd}
  6 expect "zhoulijun@192.168.8.66's password:" {send "C9yiM4dy0QMT\r"}
  7 expect eof