#!/usr/bin/expect
set timeout -1
set file_name [lindex $argv 0]
set remote_pwd [lindex $argv 1]
spawn scp -r $file_name zhoulijun@192.168.8.66:${remote_pwd}
expect "zhoulijun@192.168.8.66's password:" {send "C9yiM4dy0QMT\r"}
expect eof